### ISSUE TITLE
Problems with build process.

### ISSUE THREAD

**Issue by 0xE282B0** [voigt/private-timeline#1]
I tried to
- clone the repo
- npm install
- copy node-webkit to resources/node-webkit/MacOS64/
- run grunt dist-mac --force
  the result is an app that displays:
  
  > Uncaught Error: Cannot find module 'address_bar'", source: module.js (338)

**Comment by voigt** [comment]
Could you please [pastbin](http://pastebin.com/) your whole installation process?

**Comment by 0xE282B0** [comment]
You can find the log [here](https://github.com/voigt/private-timeline/blob/yeoman-generated/build.log).
